# National Parks EDA

This notebook explores U.S. National Parks data using Pandas. 
The goal is to answer key questions about visits and park distribution.

In [1]:
import pandas as pd

parks_data_df = pd.read_csv(
    'https://raw.githubusercontent.com/melaniewalsh/responsible-datasets-in-context/main/datasets/national-parks/US-National-Parks_RecreationVisits_1979-2023.csv'
)

In [2]:
parks_data_df.head()
parks_data_df.info()
parks_data_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 2783 entries, 0 to 2782
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ParkName          2783 non-null   str
 1   Region            2783 non-null   str
 2   State             2783 non-null   str
 3   Year              2783 non-null   int64
 4   RecreationVisits  2783 non-null   int64
dtypes: int64(2), str(3)
memory usage: 108.8 KB

              Year  RecreationVisits
count  2783.000000      2.783000e+03
mean   2001.281351      1.153497e+06
std      12.903038      1.545472e+06
min    1979.000000      0.000000e+00
25%    1990.000000      2.534695e+05
50%    2001.000000      6.112520e+05
75%    2012.000000      1.428313e+06
max    2023.000000      1.416155e+07

In [3]:
import re

def split_on_uppercase(name):
    return re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()

parks_data_df.columns = [split_on_uppercase(col) for col in parks_data_df.columns]

In [4]:
parks_data_df.groupby('state')['recreation_visits'].mean().reset_index()

   state  recreation_visits
0     AK       1.400870e+05
1     AR       1.409689e+06
2     AS       1.495650e+04
3     AZ       1.855835e+06
4     CA       9.899741e+05
5     CO       1.055443e+06
6     FL       4.787970e+05
7     HI       1.300197e+06
8     IN       1.853265e+06
9     KY       1.293298e+06
10    ME       2.980293e+06
11    MI       2.012542e+04
12    MN       2.222926e+05
13    MO       2.416309e+06
14    MT       2.070991e+06
15    ND       5.321447e+05
16    NM       5.434571e+05
17    NV       8.537689e+04
18    OH       2.195553e+06
19    OR       4.862522e+05
20    SC       9.958415e+04
21    SD       8.177507e+05
22    TN       9.770010e+06
23    TX       2.514962e+05
24    UT       1.162233e+06
25    VA       1.519811e+06
26    VI       5.545470e+05
27    WA       1.495946e+06
28    WV       1.036167e+06
29    WY       2.791162e+06

In [5]:
parks_data_df.groupby('park_name')['recreation_visits'].mean().reset_index()

                       park_name  recreation_visits
0                      Acadia NP       2.980293e+06
1                      Arches NP       8.816686e+05
2                    Badlands NP       1.021290e+06
3                    Big Bend NP       3.216910e+05
4                    Biscayne NP       4.625698e+05
..                           ...                ...
58                  Wind Cave NP       6.142118e+05
59  Wrangell-St. Elias NP & PRES       4.857088e+04
60                Yellowstone NP       3.097660e+06
61                   Yosemite NP       3.460200e+06
62                       Zion NP       2.647042e+06

[63 rows x 2 columns]

In [6]:
parks_data_df.groupby('state')['park_name'].nunique().reset_index()

   state  park_name
0     AK          8
1     AR          1
2     AS          1
3     AZ          3
4     CA          9
5     CO          4
6     FL          3
7     HI          2
8     IN          1
9     KY          1
10    ME          1
11    MI          1
12    MN          1
13    MO          1
14    MT          1
15    ND          1
16    NM          2
17    NV          1
18    OH          1
19    OR          1
20    SC          1
21    SD          2
22    TN          1
23    TX          2
24    UT          5
25    VA          1
26    VI          1
27    WA          3
28    WV          1
29    WY          2